"""get all models up to date

Revision ID: 218b1b4270d2
Revises: c17e467838d1
Create Date: 2026-01-08 18:30:18.633496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218b1b4270d2'
down_revision: Union[str, Sequence[str], None] = 'c17e467838d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_user_id'), table_name='intents')
    op.drop_table('intents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('focus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gn_search_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intents_pkey'))
    )
    op.create_index(op.f('ix_intents_user_id'), 'intents', ['user_id'], unique=False)
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    # ### end Alembic commands ###
