"""make search_history country_code nullable

Revision ID: 5863570224c1
Revises: 0c373d3c3fad
Create Date: 2026-01-08 18:40:22.878519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5863570224c1'
down_revision: Union[str, Sequence[str], None] = '0c373d3c3fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_id'), table_name='intent')
    op.drop_index(op.f('ix_intent_user_id'), table_name='intent')
    op.drop_table('intent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('focus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gn_search_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intent_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intent_pkey'))
    )
    op.create_index(op.f('ix_intent_user_id'), 'intent', ['user_id'], unique=False)
    op.create_index(op.f('ix_intent_id'), 'intent', ['id'], unique=False)
    # ### end Alembic commands ###
