"""make search_history city nullable

Revision ID: 799a9e91928a
Revises: 218b1b4270d2
Create Date: 2026-01-08 18:37:07.666602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799a9e91928a'
down_revision: Union[str, Sequence[str], None] = '218b1b4270d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_id'), table_name='intent')
    op.drop_index(op.f('ix_intent_user_id'), table_name='intent')
    op.drop_table('intent')
    op.alter_column('search_history', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'focus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_history', 'focus',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('intent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('focus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gn_search_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intent_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intent_pkey'))
    )
    op.create_index(op.f('ix_intent_user_id'), 'intent', ['user_id'], unique=False)
    op.create_index(op.f('ix_intent_id'), 'intent', ['id'], unique=False)
    # ### end Alembic commands ###
