"""Add audio_filename to audio_briefings

Revision ID: aebd523cf919
Revises: 279982cf9329
Create Date: 2026-01-11 17:52:19.262279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebd523cf919'
down_revision: Union[str, Sequence[str], None] = '279982cf9329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_id'), table_name='intent')
    op.drop_index(op.f('ix_intent_user_id'), table_name='intent')
    op.drop_table('intent')

    op.add_column('audio_briefings', 
                  sa.Column('audio_filename', sa.String(), nullable=True),
                  )
    
    op.execute(
        "UPDATE audio_briefings SET audio_filename = 'unknown.mp3' WHERE audio_filename IS NULL"
    )

    op.alter_column(
        "audio_briefings",
        "audio_filename",
        nullable=False,
    )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_history', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audio_briefings', 'audio_filename')
    op.create_table('intent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('focus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gn_search_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intent_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intent_pkey'))
    )
    op.create_index(op.f('ix_intent_user_id'), 'intent', ['user_id'], unique=False)
    op.create_index(op.f('ix_intent_id'), 'intent', ['id'], unique=False)
    # ### end Alembic commands ###
