"""Add query column to audio_briefings

Revision ID: c17e467838d1
Revises: 
Create Date: 2026-01-08 17:34:56.739826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c17e467838d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) Clean up audio_briefings -> intents link
    op.drop_index(op.f('ix_audio_briefings_intent_id'), table_name='audio_briefings')
    op.drop_constraint(op.f('audio_briefings_intent_id_fkey'), 'audio_briefings', type_='foreignkey')
    op.drop_column('audio_briefings', 'intent_id')

    # 2) Drop intents table + its indexes
    op.drop_index(op.f('ix_intents_id'), table_name='intents')
    op.drop_index(op.f('ix_intents_user_id'), table_name='intents')
    op.drop_table('intents')

    # 3) Add new columns + FK on audio_briefings
    op.add_column('audio_briefings', sa.Column('search_history_id', sa.Uuid(), nullable=True))
    op.add_column('audio_briefings', sa.Column('query', sa.String(), nullable=False))
    op.create_index(op.f('ix_audio_briefings_search_history_id'), 'audio_briefings', ['search_history_id'], unique=False)
    op.create_foreign_key(None, 'audio_briefings', 'search_history', ['search_history_id'], ['id'])

    # 4) Backfill existing NULLs in search_history so NOT NULL is allowed
    op.execute("UPDATE search_history SET city = '' WHERE city IS NULL;")
    op.execute("UPDATE search_history SET country = '' WHERE country IS NULL;")
    op.execute("UPDATE search_history SET country_code = '' WHERE country_code IS NULL;")
    op.execute("UPDATE search_history SET timeframe = 'unspecified' WHERE timeframe IS NULL;")
    op.execute("UPDATE search_history SET focus = 'general' WHERE focus IS NULL;")

    # 5) Tighten search_history columns
    op.alter_column('search_history', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('search_history', 'focus',
               existing_type=sa.VARCHAR(),
               nullable=False)




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_history', 'focus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'timeframe',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('search_history', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('audio_briefings', sa.Column('intent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audio_briefings', type_='foreignkey')
    op.create_foreign_key(op.f('audio_briefings_intent_id_fkey'), 'audio_briefings', 'intents', ['intent_id'], ['id'])
    op.drop_index(op.f('ix_audio_briefings_search_history_id'), table_name='audio_briefings')
    op.create_index(op.f('ix_audio_briefings_intent_id'), 'audio_briefings', ['intent_id'], unique=False)
    op.drop_column('audio_briefings', 'query')
    op.drop_column('audio_briefings', 'search_history_id')
    op.create_table('intents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('focus', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('intents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intents_pkey'))
    )
    op.create_index(op.f('ix_intents_user_id'), 'intents', ['user_id'], unique=False)
    op.create_index(op.f('ix_intents_id'), 'intents', ['id'], unique=False)
    # ### end Alembic commands ###
